microserviceName: "identity"

image:
  repository: jeevplayeconomy.azurecr.io/play.identity
  tag: 1.0.14

envVariables: 
   ServiceSettings__MessageBroker: SERVICEBUS
   ServiceSettings__KeyVaultName: jeevplayeconomy
   IdentitySettings__PathBase: /identity-svc
   IdentitySettings__CertificateCerFilePath: "/certificates/certificate.crt"
   IdentitySettings__CertificateKeyFilePath: "/certificates/certificate.key"
   IdentityServerSettings__Clients__0__RedirectUris__0: https://jeevplayeconomy.eastus.cloudapp.azure.com/authentication/login-callback
   IdentityServerSettings__Clients__0__PostLogoutRedirectUris__0: https://jeevplayeconomy.eastus.cloudapp.azure.com/authentication/logout-callback

resources:
  limits:
    memory: "128Mi"
    cpu: "150m"

container:
  port: 5002
  liveness:
    path: /health/live
    initialDelaySeconds: 10
  readiness:
    path: /health/ready
    initialDelaySeconds: 10
  volumeMounts:
  - name: certificate-volume
    mountPath: /certificates

volumes:
  - name: certificate-volume
    secret:
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

service:
  type: ClusterIP
  port: 80

certificate:
  secretName: signing-cert
  hostname: jeevplayeconomy.eastus.cloudapp.azure.com